spring:
  # Database for Docker
  #datasource:
  #url: jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:auto_auth_db}
  #username: ${DB_USERNAME:postgres}
  #password: ${DB_PASSWORD:postgres}

  # Consul Discovery
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        hostname: auto-car-service
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        service-name: ${spring.application.name}

# Logging for debugging
logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.springframework.web: INFO